import type { Metadata } from 'next'
import React from 'react'
import './globals.css'
import NextAuthSessionProvider from '@/providers/sessionProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className="font-work flex flex-col w-full h-[100vh] bg-white">
        <NextAuthSessionProvider>
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
